### ISSUE TITLE
Error: __dirname is not defined

### ISSUE THREAD

**Issue by EdieLemoine** [pmowrer/semantic-release-monorepo#150]
Hello!

When trying to run semantic-release with this plugin:

```
npx semantic-release --dry-run --debug
```

I get the following error:

```
[semantic-release] › ✘  An error occurred while running semantic-release: ReferenceError: __dirname is not defined
    at file://<root>/node_modules/semantic-release-monorepo/src/log-plugin-version.js:9:47
    at semantic-release-monorepo (file://<root>/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:59:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validator (file://<root>/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file://<root>/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file://<root>/node_modules/p-reduce/index.js:15:44) {
  pluginName: '[Function: semantic-release-monorepo]'
}
ReferenceError: __dirname is not defined
    at file://<root>/node_modules/semantic-release-monorepo/src/log-plugin-version.js:9:47
    at semantic-release-monorepo (file://<root>/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:59:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validator (file://<root>/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file://<root>/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file://<root>/node_modules/p-reduce/index.js:15:44) {
  pluginName: '[Function: semantic-release-monorepo]'
}node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
```

### Project structure

I'm using Yarn 4, have `"type": "module"` in each of my `package.json` files. `apps/delivery-options` is the only package I'm going to be releasing. It contains a `release.config.cjs`.

```
.
├── apps
│   ├── delivery-options <- trying to release this package
│   └── sandbox <- private
├── libs
│   ├── build-vite <- private
│   └── shared <- private
├── nx.json
├── package.json
├── tsconfig.base.json
├── tsconfig.json
└── yarn.lock
```

### Configuration

`semantic-release --debug` output

```
  semantic-release:config options values: {
  semantic-release:config   branches: [
  semantic-release:config     '(\\d+)(\\.\\d+)?\\.x',
  semantic-release:config     'master',
  semantic-release:config     'main',
  semantic-release:config     { name: 'alpha', prerelease: true },
  semantic-release:config     { name: 'beta', prerelease: true },
  semantic-release:config     { name: 'next', prerelease: true },
  semantic-release:config     { name: 'rc', prerelease: true }
  semantic-release:config   ],
  semantic-release:config   repositoryUrl: 'https://github.com/myparcelnl/delivery-options.git',
  semantic-release:config   tagFormat: '@myparcel/delivery-options-v${version}',
  semantic-release:config   plugins: [
  semantic-release:config     [ '@semantic-release/commit-analyzer', [Object] ],
  semantic-release:config     [ '@semantic-release/exec', [Object] ],
  semantic-release:config     [ '@semantic-release/release-notes-generator', [Object] ],
  semantic-release:config     [ '@semantic-release/changelog', [Object] ],
  semantic-release:config     [ '@semantic-release/github', {} ],
  semantic-release:config     [ '@semantic-release/git', [Object] ]
  semantic-release:config   ],
  semantic-release:config   analyzeCommits:  [ /* */ ],
  semantic-release:config   fail: [ [ /* */ ],
  semantic-release:config   generateNotes:  [ /* */ ],
  semantic-release:config   success: [ /* */ ],
  semantic-release:config   preset: 'conventionalcommits',
  semantic-release:config   _: [],
  semantic-release:config   'dry-run': true,
  semantic-release:config   d: true,
  semantic-release:config   dryRun: true,
  semantic-release:config   debug: true,
  semantic-release:config   '$0': '<root>/node_modules/.bin/semantic-release'
  semantic-release:config }
```

### Workaround

I've managed to fix this error for now by adding this to the top of my `release.config.cjs`:

```js
global.__dirname = __dirname;
```

**Comment by pmowrer** [comment]
Thanks for the report! Should be fixed in https://github.com/pmowrer/semantic-release-monorepo/releases/tag/v8.0.2
