### ISSUE TITLE
How to enable git/changelog plugins?

### ISSUE THREAD

**Issue by milesj** [pmowrer/semantic-release-monorepo#69]
First off, great lib, it's working flawlessly on our monorepo.

That being said, we're looking to experiment with the `git` plugin (to sync our package.json files) and the `changelog` plugin (to log each package individually). I can't seem to get either of these to run.

I've tried both:

```
module.exports = {
  extends: 'semantic-release-monorepo',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/changelog',
      {
        changelogFile: 'CHANGELOG.md',
        changelogTitle: 'Changelog',
      },
    ],
    '@semantic-release/npm',
    [
      '@semantic-release/git',
      {
        assets: ['CHANGELOG.md', 'package.json', 'packages/*/*/package.json'],
        // eslint-disable-next-line no-template-curly-in-string
        message: 'Build: ${nextRelease.gitTag} [skip ci]',
      },
    ],
    '@semantic-release/github',
  ],
};
```

And under the monorepo property:

```
module.exports = {
  extends: 'semantic-release-monorepo',
  monorepo: {
    plugins: [
      '@semantic-release/commit-analyzer',
      '@semantic-release/release-notes-generator',
      [
        '@semantic-release/changelog',
        {
          changelogFile: 'CHANGELOG.md',
          changelogTitle: 'Changelog',
        },
      ],
      '@semantic-release/npm',
      [
        '@semantic-release/git',
        {
          assets: ['CHANGELOG.md', 'package.json', 'packages/*/*/package.json'],
          // eslint-disable-next-line no-template-curly-in-string
          message: 'Build: ${nextRelease.gitTag} [skip ci]',
        },
      ],
      '@semantic-release/github',
    ],
  },
};
```

With no luck. Assuming this isn't supported atm.

**Comment by peeter-tomberg** [comment]
Any luck with this?

**Comment by milesj** [comment]
I ended up switching to lerna since you can basically auto-release with it using `--yes` and conventional changelog.

**Comment by pmowrer** [comment]
This wasn't working because this library didn't support the `plugins` option introduced in `semantic-release` v15.11. This has gotten fixed in [v7.0.0](https://github.com/pmowrer/semantic-release-monorepo/releases/tag/v7.0.0).

**Comment by ajs139** [comment]
@pmowrer - i get this when running the above plugins, and it works perfectly without the plugins:
```
[10:48:51 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:687:3)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/user/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:31:24
    at validator (/home/user/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/user/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at next (/home/user/node_modules/semantic-release/node_modules/p-reduce/index.js:17:9)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
```
any ideas?

**Comment by pmowrer** [comment]
@ajs139 Thanks for the report! It should hopefully be fixed in the latest version - let me know!

**Comment by ajs139** [comment]
@pmowrer - thanks, that works a treat! 🎉
